# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef23adbd9e38193c17c5216d59031f81452e564e0395a9005c87e7321326788084c2ed6ac6b2e65ef9775f57d78e2ac0ed5163ba57ce2831c4173828da8c965

test:
  secret_key_base: 9b0bb5228273afc9c62858f00b6ec7c8ccc38c10cc42e677c60b0c091c7be54d170ef3163c890f3dbe84898680dfe6673bf9a9483a370460e15215cd0c13c6c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
